---
- hosts: all
  become: true
  tasks:
  - name: building docker image
    command: docker build -t module2-igp .
    args:
      chdir: /home/edureka

  - name: creating docker image using docker command
    command: docker run -d --name module2-container -p 8097:8080 module2-igp

