apiVersion: v1
kind: Service
metadata:
  name: abct-service
  labels:
    app: abct-devops-project
    
spec:
  selector:
    app: abct-devops-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200    


    
